name: Defcon
version: '${project.version}'
main: com.mochibit.defcon.Defcon
api-version: 1.19
authors: [ Rynoooo, Corvinoo ]
description: A plugin that adds nuclear energy, along with his advantages and dangers
website: http://rynotechblog.altervista.org/
load: STARTUP
depend: [WorldGuard, WorldEdit, Vault, ProtocolLib]
commands:
  ncgive:
    description: Give a nuclear craft item
    permission: defcon.admin
    permission-message: You do not have permission!
    usage: /<command> [id]
  ncirradiatezone:
    description: Irradiate a zone
    permission: defcon.admin
    permission-message: You do not have permission!
    usage: /<command> [x] [y] [z] [radius]
  nctestexpl:
    description: Spawn a nuclear explosion
    permission: defcon.admin
    permission-message: You do not have permission!
    usage: /<command> [x] [y] [z]
  ncstructuresearch:
    description: Search a structure by block coordinate
    permission: defcon.admin
    permission-message: You do not have permission!
    usage: /<command> [x] [y] [z]